[versions]

java = "17"
antlr4Adaptor = "0.2.0"
antlr4 = "4.13.2"
karmaConventions = "1.8.1" # https://github.com/karmakrafts/karma-conventions/tags
intelliJPlatform = "2.10.5" # https://github.com/JetBrains/intellij-platform-gradle-plugin/releases
gradleNexus = "2.0.0" # https://github.com/gradle-nexus/publish-plugin/releases
dokka = "2.1.0" # https://github.com/Kotlin/dokka/releases
junit = "4.13.2" # TODO: update
openTest4j = "1.3.0" # TODO: update/replace

[libraries]

antlr4-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr4" }
junit = { module = "junit:junit", version.ref = "junit" }
openTest4j = { module = "org.opentest4j:opentest4j", version.ref = "openTest4j" }

[plugins]

karmaConventions = { id = "dev.karmakrafts.conventions.karma-conventions", version.ref = "karmaConventions" }
gradleNexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradleNexus" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }